# Data Manipulation

---
##Case Study: Hotel Bookings
**Objective:**

In this notebook, we are going to go through some data manipulation techniques, which are:
- Sorting Pandas DataFrame
- Subsetting columns
- Subsetting rows
- Adding a new column
- Aggregating Data
- Group by
- Pivotting
- Setting and Removing Index
- Cross Tabbing

## Dataset Explanation
- **hotelHotel:** (H1 = Resort Hotel or H2 = City Hotel)
- **is_canceled:** Value indicating if the booking was canceled (1) or not (0)
- **lead_time:** Number of days that elapsed between the entering date of the booking into the PMS and the arrival date
- **arrival_date_year:** Year of arrival date
- **arrival_date_month:** Month of arrival date
- **arrival_date_week_number:** Week number of year for arrival date
- **arrival_date_day_of_month:** Day of arrival date
- **stays_in_weekend_nights:** Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel
- **stays_in_week_nights:** Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel
- **adults:** Number of adults
- **children:** Number of children
- **babies:** Number of babies
- **meal:** Type of meal booked. Categories are presented in standard hospitality meal packages: Undefined/SC – no meal package; BB – Bed & Breakfast; HB – Half board (breakfast and one other meal – usually dinner); FB – Full board (breakfast, lunch and dinner)
- **country:** Country of origin. Categories are represented in the ISO 3155–3:2013 format
- **market_segment:** Market segment designation. In categories, the term “TA” means “Travel Agents” and “TO” means “Tour Operators”
- **distribution_channel:** Booking distribution channel. The term “TA” means “Travel Agents” and “TO” means “Tour Operators”
- **is_repeated_gues:t** Value indicating if the booking name was from a repeated guest (1) or not (0)
- **previous_cancellations:**  Number of previous bookings that were cancelled by the customer prior to the current booking
- **previous_bookings_not_canceled:** Number of previous bookings not cancelled by the customer prior to the current booking
- **reserved_room_type:** Code of room type reserved. Code is presented instead of designation for anonymity reasons.
- **assigned_room_type:** Code for the type of room assigned to the booking. Sometimes the assigned room type differs from the reserved room type due to hotel operation reasons (e.g. overbooking) or by customer request. Code is presented instead of designation for anonymity reasons.
- **booking_changes:**  Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation
- **deposit_type:** Indication on if the customer made a deposit to guarantee the booking. This variable can assume three categories: No Deposit – no deposit was made; Non Refund – a deposit was made in the value of the total stay cost; Refundable – a deposit was made with a value under the total cost of stay.
- **agent:** ID of the travel agency that made the booking
- **company:** ID of the company/entity that made the booking or responsible for paying the booking. ID is presented instead of designation for anonymity reasons
- **days_in_waiting_list:** Number of days the booking was in the waiting list before it was confirmed to the customer
- **customer_type:** Type of booking, assuming one of four categories: Contract - when the booking has an allotment or other type of contract associated to it; Group – when the booking is associated to a group; Transient – when the booking is not part of a group or contract, and is not associated to other transient booking; Transient-party – when the booking is transient, but is associated to at least other transient booking
- **adr:** Average Daily Rate as defined by dividing the sum of all lodging transactions by the total number of staying nights
- **required_car_parking_spaces:** Number of car parking spaces required by the customer
- **total_of_special_requests:** Number of special requests made by the customer (e.g. twin bed or high floor)
- **reservation_status:** Reservation last status, assuming one of three categories: Canceled – booking was canceled by the customer; Check-Out – customer has checked in but already departed; No-Show – customer did not check-in and did inform the hotel of the reason why
- **reservation_status_date:** Date at which the last status was set. This variable can be used in conjunction with the Reservation Status to understand when was the booking canceled or when did the customer checked-out of the hotel

# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset

After you download the **hotel_bookings.csv** dataset file, upload it to your runtime so you can work with it.

In [2]:
df=pd.read_csv('hotel_bookings.csv')

In [3]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

# Sorting Pandas DataFrames

## sort by one column desc order

In [4]:
data_sorted = df.sort_values('stays_in_weekend_nights', ascending=False)
data_sorted.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
14038,Resort Hotel,0,126,2016,July,28,5,19,50,1,...,No Deposit,NaN,NaN,0,Transient,110.00,0,3,Check-Out,2016-09-12
14037,Resort Hotel,0,113,2015,August,31,1,18,42,1,...,No Deposit,NaN,NaN,0,Transient,110.50,0,3,Check-Out,2015-09-30
9839,Resort Hotel,1,322,2017,January,2,10,16,40,2,...,No Deposit,8.0,NaN,0,Transient,25.50,0,0,Canceled,2016-10-31
101794,City Hotel,0,140,2016,September,39,22,16,41,0,...,No Deposit,9.0,NaN,0,Transient,8.34,0,2,Check-Out,2016-11-18
33924,Resort Hotel,0,71,2017,January,2,10,16,40,2,...,No Deposit,196.0,NaN,0,Transient,28.79,0,0,Check-Out,2017-03-07
88017,City Hotel,0,16,2016,March,11,11,14,35,0,...,No Deposit,NaN,215.0,0,Transient-Party,0.00,0,0,Check-Out,2016-04-29
54704,City Hotel,0,206,2016,July,30,23,14,34,2,...,No Deposit,9.0,NaN,0,Transient-Party,0.00,0,1,Check-Out,2016-09-09
106561,City Hotel,0,11,2017,January,3,15,13,30,0,...,No Deposit,9.0,NaN,0,Transient,0.00,0,0,Check-Out,2017-02-27
1655,Resort Hotel,0,30,2015,September,37,7,13,33,2,...,No Deposit,240.0,NaN,0,Transient,0.00,0,1,Check-Out,2015-10-23
32589,Resort Hotel,0,1,2017,February,5,3,13,32,1,...,No Deposit,NaN,NaN,0,Transient,42.11,0,3,Check-Out,2017-03-20

## sort by 2 columns in descending order

In [5]:
data_sorted = df.sort_values(['stays_in_weekend_nights','stays_in_week_nights'], ascending=False)
data_sorted.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
14038,Resort Hotel,0,126,2016,July,28,5,19,50,1,...,No Deposit,NaN,NaN,0,Transient,110.00,0,3,Check-Out,2016-09-12
14037,Resort Hotel,0,113,2015,August,31,1,18,42,1,...,No Deposit,NaN,NaN,0,Transient,110.50,0,3,Check-Out,2015-09-30
101794,City Hotel,0,140,2016,September,39,22,16,41,0,...,No Deposit,9.0,NaN,0,Transient,8.34,0,2,Check-Out,2016-11-18
9839,Resort Hotel,1,322,2017,January,2,10,16,40,2,...,No Deposit,8.0,NaN,0,Transient,25.50,0,0,Canceled,2016-10-31
33924,Resort Hotel,0,71,2017,January,2,10,16,40,2,...,No Deposit,196.0,NaN,0,Transient,28.79,0,0,Check-Out,2017-03-07
88017,City Hotel,0,16,2016,March,11,11,14,35,0,...,No Deposit,NaN,215.0,0,Transient-Party,0.00,0,0,Check-Out,2016-04-29
54704,City Hotel,0,206,2016,July,30,23,14,34,2,...,No Deposit,9.0,NaN,0,Transient-Party,0.00,0,1,Check-Out,2016-09-09
1655,Resort Hotel,0,30,2015,September,37,7,13,33,2,...,No Deposit,240.0,NaN,0,Transient,0.00,0,1,Check-Out,2015-10-23
32589,Resort Hotel,0,1,2017,February,5,3,13,32,1,...,No Deposit,NaN,NaN,0,Transient,42.11,0,3,Check-Out,2017-03-20
106561,City Hotel,0,11,2017,January,3,15,13,30,0,...,No Deposit,9.0,NaN,0,Transient,0.00,0,0,Check-Out,2017-02-27

# Subsetting
This is sometimes known as filtering or selecting.

## filter by one column

Here, we take the condition to select rows were the column 'is_canceld' is equal to 1.

In [6]:
condition=df[df['is_canceled']==1]
condition.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.0,0,0,Canceled,2015-06-23
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.0,0,2,Canceled,2015-05-11
32,Resort Hotel,1,96,2015,July,27,1,2,8,2,...,No Deposit,NaN,NaN,0,Transient,108.3,0,2,Canceled,2015-05-29

## Subsetting rows by categorical variables

Here's an example of how we can subset based on categorical variables. <br>
We choose to capture the rows where the meals belong to specific categories.

In [7]:
meal = ['BB', 'HB', 'FB']
condition = df["meal"].isin(meal)
df[condition].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

# Group by
## What percent of *adr* we got at each meal type?

Here we need to see how much *adr* each meal type gave. <br>

**Recall:**

*adr = average daily rate*, as defined by dividing the sum of all lodging transactions by the total number of staying nights

#### Using manual calculations

We calculate *adr* with respect to each type of meal, and then we divide by the *total adr*.

In [ ]:
# Calculate total adr
adr_all = df["adr"].sum()

# Subset for meal FB , calculate total adr
meal_FB = df[df["meal"] == "FB"]["adr"].sum()

# Subset for meal BB , calc total adr
meal_BB = df[df["meal"] == "BB"]["adr"].sum()

# Subset for meal HB, calc total adr
meal_HB = df[df["meal"] == "HB"]["adr"].sum()

# Get proportion for each meal
adr_propn_by_meal = [meal_FB, meal_BB, meal_HB] / adr_all
print(adr_propn_by_meal)

[0.00715718 0.75477485 0.14312021]

#### Using group by

We group the dataframe by the variable "meal", and we take the sum of *adr* that each given meal, then divide by the *total adr*.

In [8]:
# Group by meal; calc total adr
adr_by_meal = df.groupby("meal")["adr"].sum()

# Get proportion for each type
adr_propn_by_meal = adr_by_meal / sum(adr_by_meal)
print(adr_propn_by_meal)

meal
BB           0.754775
FB           0.007157
HB           0.143120
SC           0.086107
Undefined    0.008841
Name: adr, dtype: float64

# Pivoting

The pivot table takes simple data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.

The difference between pivot tables and GroupBy can sometimes cause confusion; it helps to think of pivot tables as essentially a multidimensional version of the GroupBy aggregation.

## Pivoting on one variable

Here we have one aggregate function (default: mean) for *adr* values .

In [9]:
# Pivot for mean adr for each meal
mean_adr_by_meal = df.pivot_table(values="adr", index="meal")

# Print mean_adr_by_meal
mean_adr_by_meal.head()

                  adr
meal
BB          99.407041
FB         109.040476
HB         120.307041
SC          98.295869
Undefined   91.948306

Here we have 2 aggregate functions (mean and median) for the *adr* values.

In [10]:
# Pivot for mean and median adr for each meal
mean_med_adr_by_meal = df.pivot_table(values="adr", index="meal", aggfunc=[np.mean, np.median])
mean_med_adr_by_meal.head()

                 mean  median
                  adr     adr
meal
BB          99.407041   91.67
FB         109.040476   84.00
HB         120.307041  107.00
SC          98.295869   96.00
Undefined   91.948306   79.00

# Indexing

How to set a column as an index for your dataset ?

In [11]:
# Index df by country
country_ind = df.set_index("country")

# Look at country_ind
country_ind.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
country,,,,,,,,,,,,,,,,,,,,,
PRT,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
PRT,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
GBR,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
GBR,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
GBR,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03